### ISSUE TITLE
Error occured in Homebridge@1.3.0

### ISSUE THREAD

**Issue by ryaw3672** [C-uo/homebridge-daikin-AirPurifier#2]
Hi, Cuo

This plugin very useful.
I have a problem with using your plugin in Homebridge@1.3.0
I was able to use the previous version without any problems.....

Could you give me help, please?

**Comment by C-uo** [comment]
Hi, ryaw3672
Thank you for using this plugin.

I am very interested in the reason why it cannot work.
Could you explain the problem a little more?

**Comment by ryaw3672** [comment]
Hi, Cuo

Sorry for the delay in replying.
The latest version of Homebridge did not generate any errors. 
Therefore, there are no problems.

I apologize for the inconvenience.
