### ISSUE TITLE
怎么配置到homebridge里啊？

### ISSUE THREAD

**Issue by new1943** [C-uo/homebridge-daikin-AirPurifier#8]
怎么配置到homebridge里啊？
How to configure it into homebridge?

**Comment by C-uo** [comment]
You can install it by searching for daikin-airpurifier on the homebridge ui plugin page.
您可以通过在 homebridge ui 插件页面搜索 daikin-airpurifier 来安装它。
<img width="1157" alt="image" src="https://github.com/C-uo/homebridge-daikin-AirPurifier/assets/25507069/9e15b483-ea7b-4660-8821-f504b9e5043c">
